export default {
  login: 'Anishshettyk',
  id: 47324253,
  node_id: 'MDQ6VXNlcjQ3MzI0MjUz',
  avatar_url: 'https://avatars1.githubusercontent.com/u/47324253?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Anishshettyk',
  html_url: 'https://github.com/Anishshettyk',
  followers_url: 'https://api.github.com/users/Anishshettyk/followers',
  following_url: 'https://api.github.com/users/Anishshettyk/following{/other_user}',
  gists_url: 'https://api.github.com/users/Anishshettyk/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Anishshettyk/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Anishshettyk/subscriptions',
  organizations_url: 'https://api.github.com/users/Anishshettyk/orgs',
  repos_url: 'https://api.github.com/users/Anishshettyk/repos',
  events_url: 'https://api.github.com/users/Anishshettyk/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Anishshettyk/received_events',
  type: 'User',
  site_admin: false,
  name: 'Anish shetty k',
  company: null,
  blog: '',
  location: 'Bangalore India',
  email: null,
  hireable: null,
  bio: 'finding ways to get lazy\r\n',
  twitter_username: null,
  public_repos: 23,
  public_gists: 0,
  followers: 0,
  following: 3,
  created_at: '2019-02-04T13:48:38Z',
  updated_at: '2020-10-23T02:56:09Z',
}
